name: GXAI Hourly Worker

on:
  workflow_dispatch:
  schedule:
    - cron: '15 * * * *' # Pokreće se 15 minuta posle punog sata

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests groq

      - name: Run GXAI Script
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python main.py
